import WartaFormFields from "../../Form_Models/WartaModel.js";
const {
  wartaFields: {
    // noLayanan,
    // tandaPendaftaranKapal,
    // callSign,
    // bendera,
    // noVoyagge,
    // jenisKapal,
    // tahunPembuatan,
    // noInmarsat,
    // namaCSO,
    // telpCSO,
    gtTon,
    // dwtTon,
    // loaMeter,
    // lebarMeter,
    // draftMaxMeter,
    // drafDepanMeter,
    // drafBelakangMeter,
    // ketinggianUdaraMeter,
    // domisiliKeagenan,
    // jenisPelayaran,
    // minimumSafeManning,
    // tenagaPendorong,
    // namaOperator,
    // pjOperator,
    // siupalOperator,
    // alamatOperator,
    // namaAgen,
    // pjAgen,
    // siupalAgen,
    // alamatAgen,
    // pelabuhanAsal,
    // tanggalTiba,
    // lokasiLabuh,
    // tugBoat,
    // jenisTrayek,
    // noTrayek,
    // lintasan,
  },
} = WartaFormFields;

export default {
  // [noLayanan.name]: "",
  // [tandaPendaftaranKapal.name]: "",
  // [callSign.name]: "",
  // [bendera.name]: "",
  // [noVoyagge.name]: "",
  // [jenisKapal.name]: "",
  // [tahunPembuatan.name]: "",
  // [noInmarsat.name]: "",
  // [namaCSO.name]: "",
  // [telpCSO.name]: "",
  [gtTon.name]: "",
  // [dwtTon.name]: "",
  // [loaMeter.name]: "",
  // [lebarMeter.name]: "",
  // [draftMaxMeter.name]: "",
  // [drafDepanMeter.name]: "",
  // [drafBelakangMeter.name]: "",
  // [ketinggianUdaraMeter.name]: "",
  // [domisiliKeagenan.name]: "",
  // [jenisPelayaran.name]: "",
  // [minimumSafeManning.name]: "",
  // [tenagaPendorong.name]: "",
  // [namaOperator.name]: "",
  // [pjOperator.name]: "",
  // [siupalOperator.name]: "",
  // [alamatOperator.name]: "",
  // [namaAgen.name]: "",
  // [pjAgen.name]: "",
  // [siupalAgen.name]: "",
  // [alamatAgen.name]: "",
  // [pelabuhanAsal.name]: "",
  // [tanggalTiba.name]: "",
  // [lokasiLabuh.name]: "",
  // [tugBoat.name]: "",
  // [jenisTrayek.name]: "",
  // [noTrayek.name]: "",
  // [lintasan.name]: "",
};
